# Generated by Django 3.1.7 on 2021-03-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myevent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Altitude',
            new_name='altitude',
        ),
    ]
